### PR TITLE
feat: Add `o` label to `kind`

### PR DESCRIPTION
**Pull request by yami-beta**
ref. #13 

- Add `show_source_kind` option

### CODE REVIEW

**Comment by jsit** [comment]
This looks great, except I wonder if it should be `o` inside of the `kind` attribute. From `:h complete-items`

```
word            the text that will be inserted, mandatory
abbr            abbreviation of "word"; when not empty it is used in
                the menu instead of "word"
menu            extra text for the popup menu, displayed after "word"
                or "abbr"
info            more information about the item, can be displayed in a
                preview or popup window
kind            single letter indicating the type of completion
```

asyncomplete has been indicating the completion type with a word in square brackets, but this would be more in keeping with how Vim intends these menus to appear, it seems.

**Comment by jsit** [comment]
Maybe something like #22

**Comment by yami-beta** [comment]
I merged #22 
Is there anything else you would like to change?

**Comment by jsit** [comment]
Looks great, thanks!

**Pull request merged**
